export const START_LISTENING_FOR_EVENTS = 'START_LISTENING_FOR_EVENTS'
export const STOP_LISTENING_FOR_EVENTS = 'STOP_LISTENING_FOR_EVENTS'
export const START_RECEIVING_EVENTS = 'START_RECEIVING_EVENTS';
export const RECEIVE_EVENT = 'RECEIVE_EVENT'
export const RECEIVE_EVENTS = 'RECEIVE_EVENTS'
export const RECEIVED_PENDING_EVENT = 'RECEIVED_PENDING_EVENT'
export const RECEIVED_PENDING_EVENTS = 'RECEIVED_PENDING_EVENTS'
export const MERGE_PENDING_EVENTS = 'MERGE_PENDING_EVENTS'
export const ERROR_RECEIVING_EVENT = 'ERROR_RECEIVING_EVENT'

export const TOGGLE_EVENT_SELECTION = 'TOGGLE_EVENT_SELECTION'
export const INDEX_EVENTS_BUFFER = 'INDEX_EVENTS_BUFFER'
export const INDEX_EVENTS_BUFFER_FINISHED = 'INDEX_EVENTS_BUFFER_FINISHED'

export const PAUSE_EVENTS = 'PAUSE_EVENTS'
export const RESUME_EVENTS = 'RESUME_EVENTS'
export const SEARCH_EVENTS = 'SEARCH_EVENTS'
export const RECEIVED_SEARCH_RESULTS = 'RECEIVED_SEARCH_RESULTS'

export const RENDER_EVENTS_SUBSCRIPTION = 'RENDER_EVENTS_SUBSCRIPTION'
export const INDEX_EVENTS_SUBSCRIPTION = 'INDEX_EVENTS_SUBSCRIPTION'
