export const START_LISTENING_FOR_EVENTS = 'START_LISTENING_FOR_EVENTS'
export const RECEIVE_EVENT = 'RECEIVE_EVENT'
export const ERROR_RECEIVING_EVENT = 'ERROR_RECEIVING_EVENT'

export const TOGGLE_EVENT_SELECTION = 'TOGGLE_EVENT_SELECTION'
export const INDEX_EVENT = 'INDEX_EVENT'

export const PAUSE_EVENTS = 'PAUSE_EVENTS'
export const RESUME_EVENTS = 'RESUME_EVENTS'
